Sam fiftyone
openvinotoolkit/openvino_notebooks pull request #1138
Opened 2023-06-15 05:55 UTC by jacobmarks

- As of FiftyOne 0.21, the ubuntu issue should be resolved, so I've removed that section
- I've refactored the last section on segmenting an entire dataset - there was a subtle bug there - but now it works!

2023-06-22 00:56 UTC, ryanloney commented
It crashes here on my Windows 11, Python 3.10.11 environment: 
<img width="554" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/15709723/201db926-f14c-4809-a99a-0fd8d104f6d4">

2023-06-22 14:13 UTC, itrushkin requested changes

2023-06-22 14:13 UTC, itrushkin commented on notebooks/237-segment-anything/README.md
> +The first notebook, `237-segment-anything.ipynb`, demonstrates how to work with model in tnteractive segmentation mode and automatic segmentation mode.
``` suggestion
The first notebook, `237-segment-anything.ipynb`, demonstrates how to work with model in interactive segmentation mode and automatic segmentation mode.

2023-06-25 12:18 UTC, itrushkin commented on notebooks/237-segment-anything/237-segment-anything-fiftyone.ipynb
> +{
<p>Empty cell</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1138/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='19'/>

2023-06-25 12:18 UTC, itrushkin commented on notebooks/237-segment-anything/237-segment-anything-fiftyone.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #3.    import fiftyone as fo
</pre><p>On Ubuntu 22.04, this import fails due to https://github.com/voxel51/fiftyone/issues/1803.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1138/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='20'/>

2024-04-18 11:31 UTC, andrei-kochin commented
Closing this one due to no activity

2024-04-18 11:31 UTC, closed without merging