[Gradio] Add Gradio interface to 231-instruct-pix2pix-image-editing
openvinotoolkit/openvino_notebooks pull request #1145
Opened 2023-06-19 12:26 UTC by itrushkin

Replaces Jupyter widgets with Gradio interface for InstructPix2Pix tutorial.

2023-06-21 12:13 UTC, itrushkin commented
<p><code>share=True</code> uses network tunneling to Gradio server to forward the web interface. All calculations are executed on the host machine.</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1145/discussion/#comment-1600374981'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-06-22 00:24 UTC, ryanloney commented
It works for me, but when increasing the steps, if there is a decimal point it fails with `TypeError: 'float' object cannot be interpreted as an integer`

Here's an image I made using Arc GPU in Windows 11: 
<img width="775" alt="image" src="https://github.com/openvinotoolkit/openvino_notebooks/assets/15709723/3293d088-e80f-460d-8fa1-18576dbaf460">

2023-06-22 12:32 UTC, igor-davidyuk approved these changes
LGTM

2023-07-24 16:35 UTC, sbalandi approved these changes

2023-08-09 13:36 UTC, as-suvorov approved these changes

2023-08-10 09:46 UTC, aleksandr-mokrov requested changes

2023-08-10 09:46 UTC, aleksandr-mokrov commented on notebooks/231-instruct-pix2pix-image-editing/231-instruct-pix2pix-image-editing.ipynb
The output should be cleaned up. Especially installation output.

2023-08-17 12:00 UTC, itrushkin commented on notebooks/231-instruct-pix2pix-image-editing/231-instruct-pix2pix-image-editing.ipynb
We usually have outputs for all cells to demonstrate the execution result in the documentation. For installation, I have added `-q` key for `pip install`.

2023-08-17 12:16 UTC, aleksandr-mokrov approved these changes

2023-08-17 13:04 UTC, eaidova approved these changes

2023-08-17 13:04 UTC, merged