WIP: Modelscope text-to-video notebook
openvinotoolkit/openvino_notebooks pull request #1240
Opened 2023-08-13 10:06 UTC by itrushkin

This PR introduces modelscope model notebook
- [x] Successful model conversion
- [x] Working inference
- [ ] Documentation
- [ ] Gradio inference
- [ ] Table of contents

2023-08-18 13:11 UTC, eaidova commented on notebooks/250-zeroscope-text2video/README.md
> +The ZeroScope model is a free and open-source text-to-video model that can generate realistic and engaging videos from text descriptions. It is based on the Modelscope model, but it has been improved
please align sections in readme with other notebooks readme format

2023-08-18 15:01 UTC, sbalandi approved these changes
LGTM but I can't fully check because of low memory

2023-08-20 17:49 UTC, aleksandr-mokrov requested changes

2023-08-20 17:49 UTC, aleksandr-mokrov commented on notebooks/250-zeroscope-text2video/250-zeroscope-text2video.ipynb
`del pipe.unet
gc.collect()`

Does it give some real effect here? I checked with and without deleting and force garbage collecting and looks like there no valuable difference.

2023-08-22 18:04 UTC, aleksandr-mokrov approved these changes

2023-08-29 13:34 UTC, eaidova approved these changes

2023-08-29 14:17 UTC, merged