Split yolo v8 optimization notebooks to 3 separate
openvinotoolkit/openvino_notebooks pull request #1281
Opened 2023-08-29 17:08 UTC by sbalandi

2023-08-30 11:05 UTC, eaidova approved these changes

2023-08-30 18:41 UTC, raymondlo84 commented
Possible to have a simple demo app that runs all, but doesn't require to run all NNCF and all again?

2023-08-31 10:40 UTC, itrushkin requested changes

2023-08-31 11:31 UTC, sbalandi commented on notebooks/230-yolov8-optimization/README.md
> +For each case, it will be describes the following steps in tutorials:
done

2023-08-31 12:03 UTC, itrushkin reviewed
I am unable to submit a review in ReviewNB App.
![image](https://github.com/openvinotoolkit/openvino_notebooks/assets/76161256/d3089971-d8b8-4a26-82ce-55bf31e837b0)

2023-09-01 11:45 UTC, sbalandi commented
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1281/discussion/#comment-1701012532'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-09-01 11:45 UTC, sbalandi commented
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1281/discussion/#comment-1701044288'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-09-01 11:45 UTC, sbalandi commented
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/1281/discussion/#comment-1701044343'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-09-03 09:49 UTC, itrushkin approved these changes

2023-09-04 03:57 UTC, merged