Add CV Explainability Kit Files
openvinotoolkit/openvino_notebooks pull request #1834
Opened 2024-03-20 16:05 UTC by riacheruvu

2024-03-20 16:08 UTC, riacheruvu commented
@paularamo , could you please help with merging these changes? Thank you!

2024-03-25 12:10 UTC, adrianboguszewski commented on recipes/cv_explainability/requirements.txt
> +ultralytics
Yep. Otherwise you will wake up someday realizing that your kit stopped working suddenly.

2024-03-27 00:30 UTC, riacheruvu commented on recipes/cv_explainability/requirements.txt
> +ultralytics
Thank you for the catch! The new dependencies are now pinned, in the latest commits.

2024-03-27 00:31 UTC, riacheruvu commented
Hi @adrianboguszewski and @AnishaUdayakumar, I've made the requested changes - the PR is ready for a final review. Thank you!

2024-03-28 11:40 UTC, adrianboguszewski requested changes

2024-03-28 11:40 UTC, adrianboguszewski commented on recipes/cv_explainability/.gitattributes
> +*.avi filter=lfs diff=lfs merge=lfs -text
AVI file is an empty file, so should be fixed or removed

2024-03-28 11:45 UTC, adrianboguszewski commented
Also, the kit isn't added to the main readme file (with all kits)

2024-03-28 12:41 UTC, adrianboguszewski commented on recipes/cv_explainability/requirements.txt
>  nncf==2.7.0
openvino and nncf should be updated to 2024.0 and 2.9.0. Otherwise, I have exceptions while exporting.

2024-04-01 02:52 UTC, riacheruvu commented
Hi @adrianboguszewski, I've made the changes - please review the updated PR. Thank you!

2024-04-10 16:43 UTC, adrianboguszewski approved these changes

2024-04-10 16:44 UTC, merged