Add 208 notebook
openvinotoolkit/openvino_notebooks pull request #209
Opened 2021-08-11 17:36 UTC by Debskij

2021-08-20 17:54 UTC, ryanloney requested changes
I added a few comments. Could you please also download the JPG image from this URL as a step in the notebook? I prefer not to duplicate a 288KB file twice in the repo. 

URL: https://github.com/openvinotoolkit/openvino_notebooks/raw/main/notebooks/004-hello-detection/data/intel_rnb.jpg

2021-08-20 17:54 UTC, ryanloney commented on notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
> +    "In this tutorial optical character recognition is presented. This notebook is continuation of [004-hello-detection](../004-hello-detection) notebook.\n",
```suggestion
    "This notebook tutorial demonstrates how to perform optical character recognition. It is a continuation of the [004-hello-detection](../004-hello-detection) notebook, which shows text detection only.\n",
```

2021-08-20 17:54 UTC, ryanloney commented on notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
> +    "Now in addition of previously used [horizontal-text-detection-0001](https://docs.openvinotoolkit.org/latest/omz_models_model_horizontal_text_detection_0001.html), [text-recognition-resnet](https
```suggestion
    "The [horizontal-text-detection-0001](https://docs.openvinotoolkit.org/latest/omz_models_model_horizontal_text_detection_0001.html) and [text-recognition-resnet](https://docs.openvinotoolkit.org/latest/omz_models_model_text_recognition_resnet_fc.html) iare used together for text detection and then text recognition."
```

2021-08-20 17:54 UTC, ryanloney commented on notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
> +    "    !! $convert_command\n",
```suggestion
    "    ! $convert_command\n",
```

2021-08-20 17:54 UTC, ryanloney commented on notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
> +    "    !! $convert_command\n",
I want to show the convert output, so please change (and continue to hide the model downloader output)

2021-08-20 17:54 UTC, ryanloney commented on notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
> +    "In addition print annotation based on their position, we sort it based on their position. Closer to upper left corner it is, higher it will be prioritised.\n"
```suggestion
    "Print annotations for detected text based on their position in the input image starting from the upper left corner.\n"
```

2021-08-20 17:54 UTC, ryanloney commented on notebooks/208-optical-character-recognition/208-optical-character-recognition.ipynb
> +    "# Optical Character Recognition\n",
```suggestion
    "# Optical Character Recognition with OpenVINO\n",
```

2021-08-24 15:31 UTC, ryanloney approved these changes

2021-08-24 15:32 UTC, merged

2021-08-24 18:51 UTC, raymondlo84 commented
We should use the util functions Helena made on downloading files.

def download_file(
    url: PathLike, filename: PathLike = None, directory: PathLike = None, show_progress: bool = True
):
    """
    Download a file from a url and save it to the local filesystem. The file is saved to the
    current directory by default, or to `directory` if specified. If a filename is not given,
    the filename of the URL will be used.

    :param url: URL that points to the file to download
    :param filename: Name of the local file to save. Should point to the name of the file only,
                     not the full path. If None the filename from the url will be used
    :param directory: Directory to save the file to. Will be created if it doesn't exist
                      If None the file will be saved to the current working directory
    :param show_progress: If True, show an IPython ProgressBar.

Also, we shall print out the command and the model downloader is not showing any progress bar. I thought it was crashed and we shall have some ways to show progress there. 
===
    # Run commands, first download model than convert it to inferable 
    !! $download_command
    print('Models downloded')

===

2021-08-24 18:53 UTC, raymondlo84 commented
plt.imshow(convert_result_to_image(image, resized_image, boxes_with_annotations, conf_labels=True)) 

We may want to size it up so the result is easier to read. The text at the end is very hard to read.

2021-08-24 19:06 UTC, ryanloney commented
> plt.imshow(convert_result_to_image(image, resized_image, boxes_with_annotations, conf_labels=True))
> 
> We may want to size it up so the result is easier to read. The text at the end is very hard to read.

@Debskij - can you fix this in a new PR? ^^