Add genai notebook for whisper scenario
openvinotoolkit/openvino_notebooks pull request #2406
Opened 2024-09-23 23:30 UTC by sbalandi

Task CVS-147995

2024-09-24 11:54 UTC, sbalandi commented
I built openvino.genai from PR https://github.com/openvinotoolkit/openvino.genai/pull/883 and install openvino.genai by this way: 

pip clone https://github.com/openvinotoolkit/openvino.genai.git
git remote add whisper https://github.com/as-suvorov/openvino.genai.git
git fetch whisper
git checkout as/whisper-language-task-modes
pip install .[dev]

2024-09-25 15:53 UTC, aleksandr-mokrov commented on notebooks/whisper-asr-genai/gradio_helper.py
> +            [[str(audio_example_path), "<|en|>"]],
I would suggest using an example with non-English source audio, otherwise translation task has no sense.

2024-09-26 22:43 UTC, sbalandi commented
<p>done</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421739'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-26 22:44 UTC, sbalandi commented
<p>remove excluding</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421863'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-26 22:54 UTC, sbalandi commented
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421768) on ReviewNB
> 
> _eaidova commented on 2024-09-25T15:29:14Z_ ----------------------------------------------------------------
> 
> I think it makes sence to demonstrate data reading without hf datasets too (it is not obvious how to prepare input data for this case)

changed to reading wav file

2024-09-26 22:54 UTC, sbalandi commented on notebooks/whisper-asr-genai/gradio_helper.py
> +            [[str(audio_example_path), "<|en|>"]],
added

2024-09-26 22:58 UTC, sbalandi commented
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421797'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-26 22:59 UTC, sbalandi commented
> View / edit / reply to [this conversation](https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421831) on ReviewNB
> 
> _eaidova commented on 2024-09-25T15:29:16Z_ ----------------------------------------------------------------
> 
> I'm not sure that weight compression makes sense for whisper. it has benefit for LLMs as they have large weights stored in matmul weights, even whisper large has less then 1b parameters. Please check optimum-based notebook to see suggested quantization approach

2024-09-30 11:06 UTC, as-suvorov requested changes

2024-09-30 11:06 UTC, as-suvorov commented on notebooks/whisper-asr-genai/gradio_helper.py
> +MAX_AUDIO_MINS = 30  # maximum audio input in minutes
Whisper input time window limit is 30 seconds for now, not minutes

2024-09-30 11:06 UTC, as-suvorov commented on notebooks/whisper-asr-genai/gradio_helper.py
> +        audio_length_mins = len(inputs) / 16000 / 60
```suggestion
        audio_length_seconds = len(inputs) / 16000 / 60
```

2024-09-30 11:06 UTC, as-suvorov commented on .ci/skipped_notebooks.yml
> +        - macos-12
It doesn't work on mac?

2024-09-30 11:10 UTC, as-suvorov commented on notebooks/whisper-asr-genai/gradio_helper.py
> +MAX_AUDIO_MINS = 30  # maximum audio input in minutes
I git it mixed up, please ignore above comment

2024-09-30 16:32 UTC, eaidova commented
<p>I belive for now we still need device excluding for NPU (until static pipeline for NPU will not be added in GenAI)</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421863'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-30 16:34 UTC, eaidova commented
<p>as you have significant accuracy drop related to small models, I think maybe better to not demonstrate accuracy validation (possibly it can be improved changing smooth_quant_alpha parameter for quantization)</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2382860050'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-30 19:14 UTC, sbalandi commented
<p>added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2383673634'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-30 19:14 UTC, sbalandi commented
<p>added</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2374421863'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-30 19:16 UTC, sbalandi commented
<p>changed mooth_quant_alpha to 0.80 for encoder, thank you !</p>

---

 <a href='https://app.reviewnb.com/openvinotoolkit/openvino_notebooks/pull/2406/discussion/#comment-2382860050'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2024-09-30 19:17 UTC, sbalandi commented on .ci/skipped_notebooks.yml
> +        - macos-12
it works, removed, thank you !

2024-10-01 04:08 UTC, eaidova commented on .ci/skipped_notebooks.yml
> +        - '3.8'
we dropped python3.8 support from notebooks, so it should not be required to add. What the issue with python3.9?

2024-10-01 04:09 UTC, eaidova commented on notebooks/whisper-asr-genai/README.md
> +3. Convert the model using OpenVINO Integration with HuggingFace Optimum.
quantization step and mention nncf missed

2024-10-01 10:52 UTC, eaidova approved these changes

2024-10-01 11:06 UTC, as-suvorov approved these changes

2024-10-01 12:43 UTC, aleksandr-mokrov approved these changes

2024-10-01 12:58 UTC, merged