Add facies segmentation demo
openvinotoolkit/openvino_notebooks pull request #46
Opened 2021-04-26 21:42 UTC by alexeyhorkin

I want to add facies segmentation demo =)

2021-04-27 11:51 UTC, dkurt commented on notebooks/202-facies-segmentation/README.md
> +```
Do you mind to move all these steps to the notebook? So user will have everything in a single place

2021-04-27 15:23 UTC, alexeyhorkin commented
@ryanloney, please, review)

2021-04-27 23:20 UTC, ryanloney commented
> @ryanloney, please, review)

@alexeyhorkin we do not expect the developers using the notebooks to have a C++ compiler installed. We will not be able to include the notebook unless it can be run with the Python API for inference engine. The API is already installed using "openvino-dev" when the user installs requirements.txt. 

From early feedback, we plan to use the same virtual environment for all notebooks to quickly move between notebooks. It seems this example requires many additional dependencies. It is probably best to host this somewhere else, unless it is possible to make changes to be more similar to the other notebooks. 

I will let @helena-intel comment also, as she is the lead developer for the notebooks. 

Also, we are planning to receive a contribution for an updated version of this notebook for Seismic Segmentation. Is it a similar use case to what you have developed? https://github.com/jarcher/openvino-demos/blob/master/energy/salt/OpenVINO-Salt.ipynb

2021-04-28 03:57 UTC, raymondlo84 commented
> @ryanloney, please, review)

=) I agree with @ryanloney as well because it created another layer of complexity for users to switch between the notebooks and thus breaks the user experiences! Remember in our webinar we explicitly talked about we care about how we use it and thus we shall also consider building a simple and easy to use interface as well.

Do you know if we can reduce the complexity of the demo further? If not, I think this also be perfect timing to work with our internal engineers to collaborate on this as @ryanloney suggested.

2021-04-28 12:24 UTC, dkurt commented
Hi @ryanloney and @raymondlo84! We already did this demo as simple as possible. The thing is the network is complicated by itself and requires custom layer. We also think that example notebook with custom layer will be useful for users due a lot of real scenarios require this feature. So we can refer our customers to the notebook as well.

2021-04-28 12:34 UTC, ryanloney commented
@dkurt it would be very useful to have a demonstration showing how to add custom layers. Do you have an example in Python that does not require C++?

2021-04-29 12:55 UTC, helena-intel commented
Thanks for the contribution, it is very valuable to show advanced use cases like custom layers with the notebooks. It is not clear in the notebook itself that this notebook demonstrates that, but that may be easily fixed by adding a bit more context in a markdown cell. Seconding Ryan's question, it would be great if there was a way to do this without requiring C++.  Is it required that the user builds this CPU extension themselves?

The notebooks are required to work on Windows, Linux and macOS, with Python 3.6-3.8. The notebook should also work with the default openvino-dev install. The only requirement I see that we do not install yet is itkwidgets - it seems we can add that to the requirements.

2021-05-11 17:37 UTC, dkurt commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "! pip install openvino-extensions==0.0.2"
Move it to the `requirements.txt`

2021-05-11 17:44 UTC, dkurt commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "                            'scruff', 'zechstein'],\n",
Please fix alignment

2021-05-12 09:43 UTC, helena-intel commented
Thanks @alexeyhorkin and @dkurt , this openvino-extensions package looks very useful. I just tried it on my Ubuntu 20.04 machine with Python 3.8 and I got a core dumped error with this code. I also tried in a new environment with just `pip install openvino-dev openvino-extensions`. Does this need anything else to work? I also notice that for now there is only a Linux package - I assume this will be released for macOS and Windows too?

```
from openvino_extensions import get_extensions_path
from openvino.inference_engine import IECore

ie = IECore()
ie.add_extension(get_extensions_path(), "CPU")
```

2021-05-13 18:19 UTC, dkurt commented
@helena-intel, good catch, thank you! We can confirm the issue and will try to fix. Although, Ubuntu 20.04 but Python 3.6 works, but not 3.8.

2021-05-14 16:36 UTC, helena-intel commented
I can now run the notebook on Ubuntu 20, with the new openvino-extensions package. Very cool! There are still cells with `wget` that will not work (by default) on Windows, but I am making standard functions for all notebooks to download models and data,  which I hope to have ready early next week. So no action needed there for now.

The itkwidgets visualization is great! Sadly it does not currently work in Jupyter Lab, but according to https://github.com/InsightSoftwareConsortium/itkwidgets/issues/405 a fix is "on the agenda" so that should be okay. Could you add a 2D visualition before the 3D visualization @alexeyhorkin ? That would be very useful. For example a slice from every "plane" plotted with matplotlib. That is also useful for verifying that everything is correct. If you changed a few things in the code, a 2D view makes it easier to confirm that the prediction still looks correct than a 3D result does.

I had two minor issues: 1) I needed to remove the `! cd notebooks/202-facies-segmentation` step. Do you need this step in your setup? For me it worked as expected in both Jupyter Lab and Jupyter Notebook if I just leave out this step. The current directory is the notebook directory. 2) The colormap did not work for me. I commented out the lines refering to that, like `viewer_orig_data.cmap = np.array([[i/count_of_greys, i/count_of_greys, i/count_of_greys] for i in range(count_of_greys)])` and then it worked fine. That was the only issue I had. It is possible that it was caused by a version conflict - I only installed itkwidgets and openvino-extensions. I saw that there are many pinned packages in your requirements.txt, but for now we want the notebooks to also work with the standard openvino_notebooks requirements.txt. Can you add itkwidgets and openvino-extensions to the main requirements.txt?

2021-05-20 11:55 UTC, helena-intel commented
Thanks again @alexeyhorkin ! This is looking great. I really like the 2D visualization too. I would prefer if the images are side by side (subplots(1,2) instead of (2,1), but I am also working on standard functions for showing segmentation maps and we may swap this with that when that is ready, if that is okay by you. 
<img src="https://user-images.githubusercontent.com/77325899/118968941-c7863500-b96c-11eb-8396-e62c11848060.png" width=300>

## itkwidgets
The itkwidgets doesn't work yet in Jupyter Lab, but they are working on that. It is okay by me to use this as is, but could you add a comment in the README that for now the 3D visualization does not yet work in Jupyter Lab, and to use `jupyter notebook` instead, and something similar in the notebook itself, with a note that from Jupyter Lab you can do Help->Launch Classic Notebook? I would even put that note both at the top and right before the visualization, because many people skip over text.

## openvino extensions
Most important next step is to get openvino-extensions working on all supported platforms. Is that something you are working on? The CI tests Windows, Ubuntu 18, Ubuntu 20 and macOS, with Python 3.6-3.8 It should work without modification on these platforms. The notebook should also work on RHEL with Python 3.6 and 3.8. Can openvino-extensions be made to work with that? I saw that you pinned it to 0.0.2 in the requirements.txt. Is that intended? I saw that 0.0.3 is out now.  

## pip version pinnings
In general we prefer no strict version pinnings, because users may want to use OpenVINO with their existing system/tools and use the notebooks as an entrypoint for that. Also, sometimes upgrades of other tools (like Jupyter Lab), may break compatibility with pinned versions, and the other way around: we are waiting for Jupyter Lab compatibility with itkwidgets so we will need a higher version. Instead of pinning, a minimum version is preferred. 

## text
It would be really useful if you could add a bit more text. The visualization looks really cool and this is a subject that has a lot of interest. Can you add a few lines that explain the output so that it is a bit more clear to someone who does not understand anything about the topic. Like, what are these "zechstein" and "lower_ns" outputs? Also for the CPU extension. This is the only notebook that uses this for now, could you add a bit of text that explains what loading this extension allows us to do? Also, if a user loads the network on GPU or NCS2, is that a problem? (that should be in the notebook, because that is a question some users will have).

## formatting
Note about formatting: we will use black to automatically format the notebooks. It avoids discussions about format, and time cleaning up code. If you use jupyter lab you can `pip install jupyterlab-code-formatter isort black` and then click the format notebook button in the toolbar (this needs a restart from jupyter lab if you installed it from inside the notebook).  It is not required that you do this now (though I recommend it), but I'm mentioning it also so that you know not to spent time manually doing formatting cleanup.

2021-05-20 13:15 UTC, helena-intel commented
@dkurt will the openvino-extensions package be under the openvinotoolkit organization once it is production ready? And will it have an Apache license?

2021-05-20 13:19 UTC, dkurt commented
@helena-intel, good question! I think so. We can make it as a part of OpenVINO main repo, without creation of a separate repo.

2021-05-20 15:11 UTC, alexeyhorkin commented
@helena-intel , I tried with other versions of the  itkwidgets and itk packages and the visualization didn't work for me, fragile setup in this moment

2021-05-20 15:37 UTC, helena-intel commented
> @helena-intel , I tried with other versions of the itkwidgets and itk packages and the visualization didn't work for me, fragile setup in this moment

Thanks, let's leave it as is for now then, and revisit when itkwidgets gets jupyter lab 3 support.

2021-06-07 16:45 UTC, ryanloney commented
@dkurt @alexeyhorkin  since we will not have the PR merged in core openvino, could you please build the "openvino-extensions" with manylinux2010 to make it run on RHEL? We need it to work on Red Hat's Universal Base Image so it can run for OpenShift. We can worry about Windows at a later date.

2021-06-07 16:48 UTC, dkurt commented
@ryanloney, the latest version is already from `manylinux`. Also Windows and Mac packages are released.

BTW, we are going to release the extension but in contrib repo: https://github.com/openvinotoolkit/openvino_contrib/pull/149

2021-06-07 23:42 UTC, ryanloney commented
I tried running in UBI container on OpenShift and it crashes at this step: 
![image](https://user-images.githubusercontent.com/15709723/121100696-3528c280-c7af-11eb-8ea0-8cdf31518b8d.png)

It seems that loading openvino-extensions crashes. Have you run into this problem? I'm trying on Windows now as well.

2021-06-08 03:47 UTC, dkurt commented
@ryanloney, please add full error message.
Also may I ask to try swap the imports? 
```
from openvino_extensions import get_extensions_path
from openvino.inference_engine import IECore
```

2021-06-08 04:20 UTC, ryanloney commented
Here is what happens on Windows. 
![image](https://user-images.githubusercontent.com/15709723/121122206-db87be80-c7d5-11eb-84cf-56079f16ccca.png)

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-31-a9d824ddd9e2> in <module>
      1 ie = IECore()
----> 2 ie.add_extension(get_extensions_path(), "CPU")
      3 net = ie.read_network(config["model"])

ie_api.pyx in openvino.inference_engine.ie_api.IECore.add_extension()

RuntimeError: Cannot load library 'C:\Users\ryanlone\code\repos\forks\alexey\openvino_env\lib\site-packages\openvino_extensions\user_cpu_extension.dll': 127 from cwd: C:\Users\ryanlone\code\repos\forks\alexey\openvino_notebooks\notebooks\202-facies-segmentation
```

2021-06-08 04:23 UTC, ryanloney commented
> @ryanloney, please add full error message.
> Also may I ask to try swap the imports?
> 
> ```
> from openvino_extensions import get_extensions_path
> from openvino.inference_engine import IECore
> ```

There is not an error message. After this step, the kernel resets and the following cell is not executed. If I skip to the next cell and execute I get a message `NameError: name 'IECore' is not defined` because the kernel was reset. Kernel always resets here: 
```
from openvino.inference_engine import IECore
from openvino_extensions import get_extensions_path
```

2021-06-08 06:24 UTC, dkurt commented
@ryanloney, Am I right that other OpenVINO demos work fine in OpenShift? Do you use `openvino-dev`, right?

2021-06-08 07:08 UTC, helena-intel commented
> @ryanloney, Am I right that other OpenVINO demos work fine in OpenShift? Do you use `openvino-dev`, right?

That is right. The other notebooks work, and we use `openvino-dev`.

2021-06-08 17:34 UTC, helena-intel commented
CI now passes for macOS on all Python versions, which is encouraging! It fails for Ubuntu with Python 3.8 though, and also for Windows. Part of that is the Windows download with wget, which I will fix, but openvino-extensions also fails 

```
RuntimeError: Cannot load library 'C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\openvino_extensions\user_cpu_extension.dll': 127 from cwd: D:\a\openvino_notebooks\openvino_notebooks\notebooks\202-facies-segmentation
```

You can click on the CI runs above to maybe see more relevant debug information.

2021-06-19 07:04 UTC, ryanloney commented
@alexeyhorkin @dkurt the notebook still crashes for me in Red Hat UBI environment. Can you try to run it and see if you can replicate the problem? The Dockerfile we use for OpenShift is in main branch. Simply run `docker build . -t openvino_notebooks` from inside openvino_notebooks directory and then `docker run -it -p 8888:8888` to launch the notebooks. 

Here is what happens: 
<img width="898" alt="Screen Shot 2021-06-19 at 00 02 33" src="https://user-images.githubusercontent.com/15709723/122634206-b9bdef80-d091-11eb-9b3b-586d8db3da10.png">

It happens always at this step, even if I switch the order of these two lines: 
<img width="569" alt="Screen Shot 2021-06-19 at 00 03 22" src="https://user-images.githubusercontent.com/15709723/122634231-d35f3700-d091-11eb-939b-56b0aa1589b1.png">

2021-06-19 07:06 UTC, dkurt commented
@ryanloney, Both Python 3.8 and RH must be fixed by next OpenVINO release.

2021-06-30 08:13 UTC, helena-intel commented
@alexeyhorkin OpenVINO 2021.4 is released. Could you rebase or merge your branch to main?

2021-06-30 16:15 UTC, alexeyhorkin commented
@helena-intel Rebased to main

2021-07-01 05:14 UTC, ryanloney commented
It is working now in Red Hat UBI container image. I get a few errors still, but the following visualizations are created successfully. 

2D classification results:
<img width="500" alt="Screen Shot 2021-06-30 at 22 04 27" src="https://user-images.githubusercontent.com/15709723/124068272-6df33a80-d9ef-11eb-86c7-3a524ac685e2.png">

3D visualization of results: 
<img width="500" alt="Screen Shot 2021-06-30 at 22 09 00" src="https://user-images.githubusercontent.com/15709723/124068732-e78b2880-d9ef-11eb-99b4-951f18b6db19.png">

3D visualization of original:
<img width="500" alt="Screen Shot 2021-06-30 at 22 09 21" src="https://user-images.githubusercontent.com/15709723/124068759-f1ad2700-d9ef-11eb-8233-856c9bdb7ac1.png">

Here is the notebook with outputs of the executed cells: 
[facies_demo.ipynb.zip](https://github.com/openvinotoolkit/openvino_notebooks/files/6745610/facies_demo.ipynb.zip)

And these are the errors that I see: 
```
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-27-68f7ed1946c6> in <module>
      1 viewer_orig_data = view(data, shadow=False)
      2 count_of_greys = 100
----> 3 viewer_orig_data.cmap = np.array(
      4     [
      5         [i / count_of_greys, i / count_of_greys, i / count_of_greys]

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    602             raise TraitError('The "%s" trait is read-only.' % self.name)
    603         else:
--> 604             self.set(obj, value)
    605 
    606     def _validate(self, obj, value):

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in set(self, obj, value)
    576 
    577     def set(self, obj, value):
--> 578         new_value = self._validate(obj, value)
    579         try:
    580             old_value = obj._trait_values[self.name]

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    608             return value
    609         if hasattr(self, 'validate'):
--> 610             value = self.validate(obj, value)
    611         if obj._cross_validation_lock is False:
    612             value = self._cross_validate(obj, value)

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2494         if isinstance(value, self._cast_types):
   2495             value = self.klass(value)
-> 2496         value = super(Container, self).validate(obj, value)
   2497         if value is None:
   2498             return value

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   1843             return value
   1844         else:
-> 1845             self.error(obj, value)
   1846 
   1847     def info(self):

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in error(self, obj, value, error, info)
    688                     e = "The '%s' trait expected %s, not %s." % (
    689                         self.name, self.info(), describe("the", value))
--> 690                 raise TraitError(e)
    691 
    692     def get_metadata(self, key, default=None):

TraitError: The 'cmap' trait of a Viewer instance expected a list or None, not the ndarray array([[0.  , 0.  , 0.  ],
       [0.01, 0.01, 0.01],
       [0.02, 0.02, 0.02],
       [0.03, 0.03, 0.03],
       [0.04, 0.04, 0.04],
       [0.05, 0.05, 0.05],
       [0.06, 0.06, 0.06],
       [0.07, 0.07, 0.07],
       [0.08, 0.08, 0.08],
       [0.09, 0.09, 0.09],
       [0.1 , 0.1 , 0.1 ],
       [0.11, 0.11, 0.11],
       [0.12, 0.12, 0.12],
       [0.13, 0.13, 0.13],
       [0.14, 0.14, 0.14],
       [0.15, 0.15, 0.15],
       [0.16, 0.16, 0.16],
       [0.17, 0.17, 0.17],
       [0.18, 0.18, 0.18],
       [0.19, 0.19, 0.19],
       [0.2 , 0.2 , 0.2 ],
       [0.21, 0.21, 0.21],
       [0.22, 0.22, 0.22],
       [0.23, 0.23, 0.23],
       [0.24, 0.24, 0.24],
       [0.25, 0.25, 0.25],
       [0.26, 0.26, 0.26],
       [0.27, 0.27, 0.27],
       [0.28, 0.28, 0.28],
       [0.29, 0.29, 0.29],
       [0.3 , 0.3 , 0.3 ],
       [0.31, 0.31, 0.31],
       [0.32, 0.32, 0.32],
       [0.33, 0.33, 0.33],
       [0.34, 0.34, 0.34],
       [0.35, 0.35, 0.35],
       [0.36, 0.36, 0.36],
       [0.37, 0.37, 0.37],
       [0.38, 0.38, 0.38],
       [0.39, 0.39, 0.39],
       [0.4 , 0.4 , 0.4 ],
       [0.41, 0.41, 0.41],
       [0.42, 0.42, 0.42],
       [0.43, 0.43, 0.43],
       [0.44, 0.44, 0.44],
       [0.45, 0.45, 0.45],
       [0.46, 0.46, 0.46],
       [0.47, 0.47, 0.47],
       [0.48, 0.48, 0.48],
       [0.49, 0.49, 0.49],
       [0.5 , 0.5 , 0.5 ],
       [0.51, 0.51, 0.51],
       [0.52, 0.52, 0.52],
       [0.53, 0.53, 0.53],
       [0.54, 0.54, 0.54],
       [0.55, 0.55, 0.55],
       [0.56, 0.56, 0.56],
       [0.57, 0.57, 0.57],
       [0.58, 0.58, 0.58],
       [0.59, 0.59, 0.59],
       [0.6 , 0.6 , 0.6 ],
       [0.61, 0.61, 0.61],
       [0.62, 0.62, 0.62],
       [0.63, 0.63, 0.63],
       [0.64, 0.64, 0.64],
       [0.65, 0.65, 0.65],
       [0.66, 0.66, 0.66],
       [0.67, 0.67, 0.67],
       [0.68, 0.68, 0.68],
       [0.69, 0.69, 0.69],
       [0.7 , 0.7 , 0.7 ],
       [0.71, 0.71, 0.71],
       [0.72, 0.72, 0.72],
       [0.73, 0.73, 0.73],
       [0.74, 0.74, 0.74],
       [0.75, 0.75, 0.75],
       [0.76, 0.76, 0.76],
       [0.77, 0.77, 0.77],
       [0.78, 0.78, 0.78],
       [0.79, 0.79, 0.79],
       [0.8 , 0.8 , 0.8 ],
       [0.81, 0.81, 0.81],
       [0.82, 0.82, 0.82],
       [0.83, 0.83, 0.83],
       [0.84, 0.84, 0.84],
       [0.85, 0.85, 0.85],
       [0.86, 0.86, 0.86],
       [0.87, 0.87, 0.87],
       [0.88, 0.88, 0.88],
       [0.89, 0.89, 0.89],
       [0.9 , 0.9 , 0.9 ],
       [0.91, 0.91, 0.91],
       [0.92, 0.92, 0.92],
       [0.93, 0.93, 0.93],
       [0.94, 0.94, 0.94],
       [0.95, 0.95, 0.95],
       [0.96, 0.96, 0.96],
       [0.97, 0.97, 0.97],
       [0.98, 0.98, 0.98],
       [0.99, 0.99, 0.99]]).
```

```
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
<ipython-input-28-51591868d380> in <module>
      2 show_legend(config["name_classes"], cmap)
      3 viewer_interpret_data = view(predicted_data, shadow=False)
----> 4 viewer_interpret_data.cmap = cmap
      5 widgets.link(
      6     (viewer_interpret_data, "camera"), (viewer_orig_data, "camera")

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    602             raise TraitError('The "%s" trait is read-only.' % self.name)
    603         else:
--> 604             self.set(obj, value)
    605 
    606     def _validate(self, obj, value):

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in set(self, obj, value)
    576 
    577     def set(self, obj, value):
--> 578         new_value = self._validate(obj, value)
    579         try:
    580             old_value = obj._trait_values[self.name]

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in _validate(self, obj, value)
    608             return value
    609         if hasattr(self, 'validate'):
--> 610             value = self.validate(obj, value)
    611         if obj._cross_validation_lock is False:
    612             value = self._cross_validate(obj, value)

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   2494         if isinstance(value, self._cast_types):
   2495             value = self.klass(value)
-> 2496         value = super(Container, self).validate(obj, value)
   2497         if value is None:
   2498             return value

/opt/app-root/lib64/python3.8/site-packages/traitlets/traitlets.py in validate(self, obj, value)
   1843             return value
   1844         else:
-> 1845             self.error(obj, value)
   1846 
   1847     def info(self):

/opt/app-root/lib64/python3.8/site-pack [...]

2021-07-01 05:58 UTC, ryanloney commented
@alexeyhorkin who is the owner of the data from the Dropbox URLs? Is there an associated license we can reference in this notebook? If not, who do we contact to identify the license of this dataset? 

Also, we can't use wget. @helena-intel can you make a suggestion here? I found a basic Python function for downloading large files and added it to notebook_utils.py: 
```
def download_file(url, filename):
    import requests
    local_filename = filename
    with requests.get(url, stream=True) as r:
        r.raise_for_status()
        with open(local_filename, 'wb') as f:
            for chunk in r.iter_content(chunk_size=8192): 
                f.write(chunk)
    return local_filename
```

Then I changed the notebook cells: 

Download model:
```
! mkdir -p model

download_file('https://www.dropbox.com/s/x0c7ao8kebxykj1/facies-segmentation-deconvnet.bin?dl=1',\
              'model/facies-segmentation-deconvnet.bin')

download_file('https://www.dropbox.com/s/g288xdcd7xumqm7/facies-segmentation-deconvnet.xml?dl=1',\
              'model/facies-segmentation-deconvnet.xml')

download_file('https://www.dropbox.com/s/a7kge25hfpjnhvf/facies-segmentation-deconvnet.mapping?dl=1',\
              'model/facies-segmentation-deconvnet.mapping')
```

 ```
# Download dataset
! mkdir -p data
    
download_file('https://www.dropbox.com/s/sbj2atyukpjgssx/test2_seismic.npy?dl=1',\
              'data/test2_seismic.npy')
```

Should we do something like this to get it working cross-platform?

2021-07-01 08:26 UTC, alexeyhorkin commented
@ryanloney At the moment, part of the dataset (as model IR) is in my Dropbox for testing purposes. In general, the dataset is taken from here:  https://github.com/yalaudah/facies_classification_benchmark (MIT License ?)

2021-07-01 08:44 UTC, helena-intel commented
@alexeyhorkin Thanks for the rebase, great to see more tests passing. We will have a generic function library that includes downloading files soon, but could you for now change wget to curl to get this working on Windows? That will fail for Ubuntu users who did not install curl - but that is acceptable for now.

2021-07-01 19:21 UTC, helena-intel commented
Thanks @alexeyhorkin  and @dkurt, the CI now passes for all configurations! I wish the extensions were in the openvino-dev package, but this is still a great solution to make this accessible for everyone. I will  try the notebook early next week - it would be really nice if we can get the 3D visualizations to work in Jupyter Lab. @ryanloney I suppose we need a better place to store the model files. This page specifically says the data files have an MIT license so that should not be an issue https://zenodo.org/record/3755060. Alexey, could you credit the dataset authors in the notebook? They mention a preferred citation format on their Github.

2021-07-01 19:50 UTC, alexeyhorkin commented
@ryanloney on Windows Python 3.7.7 works well, I will test it on Python3.8 later, thanks

2021-07-06 10:28 UTC, alexeyhorkin commented
@ryanloney , i tested this notebook in this https://github.com/openvinotoolkit/openvino_notebooks/blob/main/Dockerfile container, it worked without any errors

2021-07-06 13:18 UTC, helena-intel commented
Tested on Windows with Python 3.7, everything works. I also added the requirements for this notebook to the Pipfile for the Docker image. I only pinned itkwidgets, pinning itk too caused issues. I assume that pinning itkwidgets will pull in a suitable itk version. It works fine in the Docker image - do you foresee issues with that @alexeyhorkin ? If we can exclude itk from requirements.txt and only pin itkwidgets that would prevent potential conflicts. Pipfile is here: https://github.com/openvinotoolkit/openvino_notebooks/blob/main/.docker/Pipfile

A few small notes:

![image](https://user-images.githubusercontent.com/77325899/124605212-f77d8f00-de6b-11eb-84dc-f12a335846db.png)
I suggest instead of args.device to give an example with GPU here, since args are not used in the notebook. Have you tested that the model works well with NCS2? Do the inference results look the same?

![image](https://user-images.githubusercontent.com/77325899/124605528-4a574680-de6c-11eb-8f09-98334fdf560a.png)
These are a lot of N/A's. Does this add anything to the visualization? If not, if it is easy to hide I suggest that.

Could you add the openvino imports to the import cell to the top? That's now in our guidelines - to have all the main requirements in the same cell.

2021-07-06 16:45 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "This demo demonstrate how to run facies classification using OpenVINO&trade;\n",
```suggestion
    "This demo demonstrates how to run facies segmentation using OpenVINO&trade;\n",
```

2021-07-06 17:07 UTC, alexeyhorkin commented
@helena-intel , i tested demo without itk in requirements.txt (local ubuntu 18.04 with Python 3.6.9 and Docker container) and for now it works fine, but as far as I remember, I specified `itk==5.1.2` because the visualization did not work, but now this is not a problem, so i removed itk but I haven't tested it on Windows yet, thanks =)

2021-07-07 18:45 UTC, helena-intel commented
@alexeyhorkin if you wrote a paper or report with this data/method and would like to link that in the notebook that might be interesting for readers who want to learn more.

2021-07-08 01:51 UTC, ryanloney requested changes
Please review and accept the proposed changes

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/README.md
> +For now the 3D visialization does not yet work in `Jupyter Lab`, please use `jupyter notebook` instead.
```suggestion
Currently, only 2D visualization is supported in `jupyter lab`, for 3D visualizations please use `jupyter notebook` instead. To switch from Jupyter Lab to classic Jupyter Notebook, select `Help` from the menu bar and then `Launch Classic Notebook`. 
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/README.md
> +This demo demonstrate how to run facies classification using OpenVINO&trade;
```suggestion
This Jupyter notebook demonstrates how to run facies segmentation with seismic data using OpenVINO&trade; Toolkit.
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "For now the 3D visialization does not yet work in `Jupyter Lab`, please use `jupyter notebook` instead.\n",
```suggestion
    "Currently, only 2D visualization is supported in `jupyter lab`, for 3D visualizations please use `jupyter notebook` instead.\n",
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "The application uses Jupyter notebook to display 3d itkwidget with resulting instance classification masks."
```suggestion
    "The application displays 3D visualization inside the Jupyter notebook using itkwidget with resulting instance classification masks."
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "Upon the start-up, the demo application loads a network and an given dataset file to the Inference Engine plugin. When inference is done, the application displays 3d itkwidget viewer with facies
```suggestion
    "At start-up, the demo application loads a network and a given dataset file to Inference Engine plugin. When inference is complete, the application displays the 3D itkwidget viewer with facies interpretation."
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "Step 1: You can install the required packages with the following command:"
```suggestion
    "Step 1: Import the required packages"
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "### Download model:\n",
```suggestion
    "### Download the model:\n",
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "Step 1: Create model folder and download a model:"
```suggestion
    "Step 1: Create a model directory and download the model:"
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "The dataset is used from here: https://github.com/yalaudah/facies_classification_benchmark"
```suggestion
    "The open source dataset used in this demo is available on GitHub: https://github.com/yalaudah/facies_classification_benchmark"
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "### Define useful functions"
```suggestion
    "### Define functions"
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "If you want to run inference on another device, such as a `GPU` or `NCS2`, you must specify the `net` variable as follows:\n",
```suggestion
    "If you want to run inference on another device, such as a `GPU` or `NCS2`, you must specify the `net` variable like the examples below:\n",
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "Different facies are identified as output classes. A facies represent a body of rock with specific characteristics that differentiate it from others.\n",
```suggestion
    "Different facies are identified as output classes. Facies represent a body of rock with specific characteristics that differentiate it from others.\n",
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "Now the inference of the model is running. Slices along the axis 1 are fed to the input and the result is combined into an output cube (`predicted_data`)."
```suggestion
    "Inference is now running on the model. Slices along axis 1 are fed to the input and the results are combined into an output cube (`predicted_data`)."
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "* Prepare origidal data viewer"
```suggestion
    "* Prepare original data viewer"
```

2021-07-08 01:51 UTC, ryanloney commented on notebooks/202-facies-segmentation/facies_demo.ipynb
> +    "You can now see a visualization of the interpreted and raw seismic data, also it is possible to interactively use your mouse to rotate or zoom in and explore interpretated data."
```suggestion
    "You can now see a visualization of the interpreted and raw seismic data. It is also possible to use your mouse to interactively rotate, zoom and explore the interpreted data."
```

2021-07-08 02:10 UTC, ryanloney commented
@dkurt @alexeyhorkin we have a request from Yury to show how to convert models in the notebooks and not just show how to use an IR that is already converted. Could you please share the source of the model so we can show how to convert it in the notebook? We can make an update after merging, but we need the original model source. Thanks.

2021-07-08 11:07 UTC, alexeyhorkin commented
@ryanloney  I have `.pth` file, I will share it with you as soon as possible.

2021-07-15 21:37 UTC, ryanloney commented
I was able to run the notebook with the 3D viz working on Red Hat test cluster in AWS. Looks good. 

I am fine to merge this @helena-intel. We need to get the model in storage.openvinotoolkit.org still, but we can add it later. 

@alexeyhorkin can you share the model source so we can reference it's origin in the repo. If you have the code in a public repo that you used to train, that is fine. If not, we can reference https://github.com/yalaudah/facies_classification_benchmark for now

Here is a screenshot running on the Red Hat cluster: 
![image](https://user-images.githubusercontent.com/15709723/125861056-52009b2d-e917-4bdb-829f-94a3bd6ddb2b.png)

2021-07-15 21:44 UTC, ryanloney approved these changes

2021-07-16 12:16 UTC, alexeyhorkin commented
@ryanloney , trained code contains on private gitlab but it basically used  https://github.com/yalaudah/facies_classification_benchmark code repo so we can reference it =)

2021-07-16 12:56 UTC, helena-intel commented
Thanks @alexeyhorkin . Can you add a reference to the source repo to the introduction and the README, and mention in the notebook that the IR model was created with Model Optimizer? Did you have to do anything special to convert the model to IR or did it just work? If it just works, we can link to the 102 pytorch/onnx conversion notebook with a "See the PyTorch/ONNX to OpenVINO IR tutorial for information on how to convert this model to OpenVINO's IR format" message. 

You mention the NCS2 in the notebook. Did you test that that works well? There are some issues with running NCS2 and notebooks - we want to have a notebook about it and hope the issues will be fixed. But for now, I suggest removing the reference. Users who have an NCS2 hopefully know that they can change the device and play with it - but then it is not something we officially support.

2021-07-16 14:24 UTC, alexeyhorkin commented
@helena-intel , about converting part - it doesn't just work, actually to convert model from ONNX to IR we used  to run `mo_onnx.py` script with special flag (--extension) as below: 
```
python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo_onnx.py \
    --input_model model.onnx \
    --extension openvino_pytorch_layers/mo_extensions

```

`openvino_pytorch_layers/mo_extensions` - this is python code from @dkurt  repo - https://github.com/dkurt/openvino_pytorch_layers

about `NCS2` i did not test it, so i will remove this mention

2021-07-19 15:09 UTC, alexeyhorkin commented
Thank you @ryanloney , @helena-intel, can you please review ?

2021-07-21 09:43 UTC, helena-intel commented
@alexeyhorkin While we generally decided on using one requirements.txt, ITKWidgets is huge (about 1GB) - which is not ideal to include for just one visualization in one notebook. Can you remove it from the requirements and make the 3D visualization optional (with an if-statement or try/except that shows 3D viz if itkwidgets is installed and otherwise shows a message saying ITKWidgets is not installed, to see 3D visualizations, please install ITKWidgets by uncommenting the following cell, where you then do `# %pip install itkwidgets`? I am sorry for this - we generally do prefer 1 requirements.txt for now but 1GB is relatively huge.

Also: can you add the note about MO that you made here https://github.com/openvinotoolkit/openvino_notebooks/pull/46#issuecomment-881489191 to the notebook, where you mention that the model was converted with MO? 

Last question: Can you rename the folder to 204-vision-facies-segmentation and the notebook to 204-vision-facies-segmentation.ipynb ?

I will merge after this. Thank you very much for all your work on this!

2021-07-22 19:40 UTC, helena-intel commented
Thanks @alexeyhorkin and also thanks @dkurt for the openvino-extensions package. It is much appreciated and we are happy to have this demo notebook!

2021-07-22 19:42 UTC, merged

2021-07-22 22:30 UTC, alexeyhorkin commented
@helena-intel , @ryanloney  Thanks! 
I missed the outdated README, I guess it is  good to update the picture (as far as I remember, you were going to make a GIF animation) and remove the text at the end because of we renamed demo notebook.

2021-07-23 08:16 UTC, helena-intel commented
Ah thanks @alexeyhorkin, I missed that too. I corrected the name at the end. We are in the process of creating/updating the READMEs for all notebooks and will include this notebook and can then create the GIF. For now, I still like the picture there - it gives an impression of the output.