215 Text Image Super Resolution with OpenVINO
openvinotoolkit/openvino_notebooks pull request #467
Opened 2022-03-14 03:08 UTC by FisherWY

This is a notebook using text image super resolution model to super resolute an image with blur text.

The flowchart is below:
![Flowchart](https://user-images.githubusercontent.com/32707008/158097956-6f1a5b80-f122-49ea-9cd6-331e7bbefeca.png)

The output image is below:
![Output](https://user-images.githubusercontent.com/32707008/158098046-575d8b7f-4b5b-45aa-a51c-6045983e269d.png)

2022-03-17 08:45 UTC, FisherWY commented
@ryanloney It seems that my understanding of what the code_check checks has gone a bit off. I thought the check was for the existence of the binder URL, so asked the mentor in the mailing list, here is the [thread](https://lists.01.org/hyperkitty/list/gsoc@lists.01.org/thread/Q66I6D5GPX3NRZ5NMUUDY7TH5GPIOONZ/). Mentor said don't worry about it, binder URL will be added after merge.
So should I now add the notebook to readme.md and notebooks/readme.md before merge?

2022-03-19 02:26 UTC, FisherWY commented
@ryanloney I have added the notebook to readme.md and notebooks/readme.md. All checks have passed in my fork repository.

2022-03-28 08:13 UTC, Debskij requested changes
Thanks for your contribution @FisherWY!

2022-03-28 08:13 UTC, Debskij commented on notebooks/215-text-image-superresolution/215-text-image-superresolution.ipynb
> +    "output_layer_ir = next(iter(compiled_model.outputs))\n",
```suggestion
    "input_layer_ir = compiled_model.input(0)\n",
    "output_layer_ir = compiled_model.output(0)\n",
```

2022-03-29 14:23 UTC, Debskij commented
Please remove .bin and .xml files from model directory and use omz_downloader instead.

2022-03-30 10:31 UTC, FisherWY commented
Model files removed and use omz_downloader instead. @Debskij

2022-03-31 15:42 UTC, Debskij approved these changes

2022-04-12 09:36 UTC, paularamo requested changes
@FisherWY Thanks for your contributions. I have requested some changes to your notebook. Please update the Readme file, and include the links to the tools you are referring to.

@ryanloney after these changes, the notebook will be ready for your final review.

2022-04-12 09:36 UTC, paularamo commented on notebooks/215-text-image-superresolution/215-text-image-superresolution.ipynb
> +    "Super Resolution is the process of enhancing the quality of an image by increasing the pixel count using deep learning. This notebook shows the Text Image Super Resolution (TISR) which takes jus
```suggestion
    "Super Resolution is the process of enhancing the quality of an image by increasing the pixel count using deep learning. This notebook shows the Text Image Super Resolution (TISR) which takes just one low resolution image with blured text, and output a high resolution image which have clear text. We use a model called [text-image-super-resolution-0001](https://github.com/openvinotoolkit/open_model_zoo/blob/master/models/intel/text-image-super-resolution-0001/README.md) which is available from the [Open Model Zoo.](https://docs.openvino.ai/latest/model_zoo.html)"
```

2022-04-12 09:36 UTC, paularamo commented on notebooks/215-text-image-superresolution/215-text-image-superresolution.ipynb
> +    "Super Resolution is the process of enhancing the quality of an image by increasing the pixel count using deep learning. This notebook shows the Text Image Super Resolution (TISR) which takes jus
Please include the links of the tools we are using in this notebook.

2022-04-12 09:36 UTC, paularamo commented on notebooks/215-text-image-superresolution/215-text-image-superresolution.ipynb
> +    "We use `omz_downloader` to download the model from open model zoo. The models in open model zoo are already converted to OpenVINO Intermediate Representation (IR), so there is no need to use `om
Please include the link to the tools you are referred to. For example https://docs.openvino.ai/latest/omz_tools_downloader.html

2022-04-12 09:36 UTC, paularamo commented on notebooks/215-text-image-superresolution/215-text-image-superresolution.ipynb
> +    "The Text Image Super Resolution model expects one input: the input shape format as (B, C, H, W), B is batch-size, C is number of channels, H is image height, W is image width. By default the inp
```suggestion
    "TISR model expects one input: the input shape format as (B, C, H, W), B is batch-size, C is number of channels, H is image height, W is image width. By default the input shape is (1, 1, 360, 640).\n",
```

2022-04-12 09:36 UTC, paularamo commented on notebooks/215-text-image-superresolution/215-text-image-superresolution.ipynb
> +    "Then we load the source image, convert to gray scale and reshape it."
```suggestion
    "Then, we load the source image, convert to gray scale and reshape it."
```

2022-04-12 12:47 UTC, FisherWY commented
@paularamo Thank you for your suggestions, I have updated the notebook and README file according to your suggestions.

2022-04-13 15:11 UTC, raymondlo84 commented
@FisherWY -- Thank you again for this PR! :) We had reviewed it and we decided not to merge because it overlaps with our existing two superres ones already (e.g., https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/207-vision-paddlegan-superresolution)

=) Keep it up and we are looking forward to seeing more interesting notebooks from you next. 

P.S., not merging is not equal to fail the requirement.

2022-04-14 07:18 UTC, FisherWY commented
> @FisherWY -- Thank you again for this PR! :) We had reviewed it and we decided not to merge because it overlaps with our existing two superres ones already (e.g., https://github.com/openvinotoolkit/openvino_notebooks/tree/main/notebooks/207-vision-paddlegan-superresolution)
> 
> =) Keep it up and we are looking forward to seeing more interesting notebooks from you next.
> 
> P.S., not merging is not equal to failing the requirement.

Understood, although the pre-trained model used in this notebook has not been used, its task is still image super resolution.
Looking forward to launch more pre-trained models for different kinds of tasks. :)

2022-04-20 15:42 UTC, closed without merging