Update 214-vision-paddle-classification.ipynb
openvinotoolkit/openvino_notebooks pull request #511
Opened 2022-03-28 16:21 UTC by OpenVINO-dev-contest

delete the notes

2022-03-28 16:22 UTC, paularamo approved these changes

2022-03-29 10:13 UTC, adrianboguszewski requested changes
- the link from notebooks/README doesn't work, please fix that

2022-03-29 10:58 UTC, OpenVINO-dev-contest commented
> * the link from notebooks/README doesn't work, please fix that

Thanks for your reminder, I will create another PR for that

2022-03-29 10:58 UTC, closed without merging

2022-03-29 13:40 UTC, paularamo commented
@OpenVINO-dev-contest you don't need to open a new PR for every request we make. I will delete this PR, please have that in mind for the next PR.