Update 214
openvinotoolkit/openvino_notebooks pull request #514
Opened 2022-03-29 10:57 UTC by OpenVINO-dev-contest

update Binder link
Delete code comments

2022-03-29 23:43 UTC, paularamo approved these changes

2022-03-30 14:22 UTC, ryanloney requested changes

2022-03-30 14:22 UTC, ryanloney commented on notebooks/214-vision-paddle-classification/214-vision-paddle-classification.ipynb
> +    "# 'latency': device performance mode will be set to LATENCY.\n",
```suggestion
    "# 'latency': device performance optimized for LATENCY.\n",
```

2022-03-30 18:57 UTC, ryanloney approved these changes

2022-03-30 18:58 UTC, ryanloney commented
@Debskij please review and approve when you can

2022-03-31 11:52 UTC, adrianboguszewski commented
The link in notebooks/README is still broken!

2022-04-01 08:42 UTC, OpenVINO-dev-contest commented
> The link in notebooks/README is still broken!

fixed ,thanks reminder

2022-04-07 15:30 UTC, merged