215 image inpainting
openvinotoolkit/openvino_notebooks pull request #546
Opened 2022-04-28 15:57 UTC by adrianboguszewski

This is a replacement for #471

2022-05-04 10:36 UTC, Debskij requested changes

2022-05-04 10:36 UTC, Debskij commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "input_layers = list(compiled_model.inputs)\n",
```suggestion
    "input_layer = compiled_model.input(0)\n",
```

2022-05-04 10:36 UTC, Debskij commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "N, H, W, C = input_layers[0].shape"
```suggestion
    "N, H, W, C = input_layer.shape"
```

2022-05-04 10:36 UTC, Debskij commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "# Store the input node names as a list because this model has 2 inputs\n",
We are not storing node names in list below

2022-05-04 10:36 UTC, Debskij commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    " 4. Get input and output names of nodes.\n",
We are not exactly storing output and input names

2022-05-04 10:36 UTC, Debskij commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "            mask: grayscale float32 mask of size [image_height,image_width,1]\n",
```suggestion
    "            mask: grayscale float32 mask of size shaped [image_height, image_width, 1]\n",
```

2022-05-05 19:35 UTC, ryanloney reviewed
Please use an Intel-related image for the notebook. I provided a suggestion. 

Also, it would be nice to save the repaired image after applying in-painting as a .png. Can you add a step for it? Otherwise this looks good to merge.

2022-05-05 19:35 UTC, ryanloney commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "url = \"https://user-images.githubusercontent.com/4547501/165946837-007d9f76-5418-41f3-92c9-2f37091b72dd.png\"\n",
```suggestion
    "url = \"https://www.intel.com/content/dam/www/central-libraries/us/en/images/arc-home-hero-128.png.rendition.intel.web.480.360.png\"\n",
```
Please change to something Intel related. If you don't like this image, please suggest an alternative

2022-05-05 19:35 UTC, ryanloney commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "    url, filename=\"waterfall.png\", directory=\"data\", show_progress=False, silent=True, timeout=30\n",
```suggestion
    "    url, filename=\"laptop.png\", directory=\"data\", show_progress=False, silent=True, timeout=30\n",
```

2022-05-05 19:35 UTC, ryanloney commented on notebooks/215-image-inpainting/215-image-inpainting.ipynb
> +    "## Image In-painting using OpenVINO\n",
```suggestion
    "## Image In-painting with OpenVINO™\n",
```

2022-05-06 15:09 UTC, ryanloney approved these changes

2022-05-06 16:01 UTC, Debskij approved these changes

2022-05-06 16:34 UTC, merged