Add tagging for notebooks
openvinotoolkit/openvino_notebooks pull request #550
Opened 2022-05-09 13:51 UTC by Debskij

In current state names of notebooks doesn't represent every single feature that is used inside of them.
This addition to CI should help entry level users to learn new features of OpenVINO in easier way.
This PR contains:
- `keywords.json` - list of tags (keywords) with their representation in code. Based on their representation in code workflow automatically assigns tag to notebook
-  `tagger.py` - simple python script capable of searching through notebooks and determining which tags should be assigned to each notebook.
- `generate_tags.yml` - workflow for running tagger and exposing json file with tags

2022-05-10 09:01 UTC, adrianboguszewski requested changes

2022-05-10 09:17 UTC, Debskij commented on .ci/keywords.json
> +        "Reshape Model": ["model.reshape("],
Due to 2.0 API changes we are using only `model` as a reference to read model.

2022-05-11 03:08 UTC, ryanloney approved these changes
Please show a demo of this tomorrow

2022-05-11 10:49 UTC, adrianboguszewski approved these changes

2022-05-11 15:57 UTC, merged