OpenVINO optimizations for Knowledge graphs embedding model (ConvE)
openvinotoolkit/openvino_notebooks pull request #555
Opened 2022-05-18 20:25 UTC by karkadad

This notebook showcases optimizations that can be obtained using the Intel OpenVINO toolkit on a Knowledge Graph embeddings model (ConvE).

We showcase the following:
1. The trained PyTorch knowledge graph embeddings model conversion for OpenVINO inference.
2. Show that there were no accuracy differences post conversion.
3. Showcase the platform specific speedup in runtime performance that can be obtained through OpenVINO graph optimizations.

I have performed manual test and code quality checks (nbval and nbqa). I have made sure to follow the coding guidelines provided here: https://github.com/openvinotoolkit/openvino_notebooks/blob/173645d14740b0ceba9d9785552823bf8330ce67/CONTRIBUTING.md#coding-guidelines .

Research paper and code attribution are also provided and I've also included the model implementation license in the Jupyter notebook.

2022-05-19 16:37 UTC, karkadad commented
@adrianboguszewski Please let me know who can review this. Thanks.

2022-05-20 20:27 UTC, karkadad commented
@ryanloney Thanks for the great feedback, I have updated the README for a bit of background context on the model and the task and then included a couple of cells on how to do prediction on the model. I've also included cells showcasing how to do prediction using benchmark_app for this model. 

As for the Windows runs, looks like some of the nbval runs successfully completed on Windows, and there is a template from other notebooks on finding cl.exe included in the notebook, however I will double check to make there are no issues.

2022-05-23 17:31 UTC, karkadad commented
@ryanloney I did additional testing on Windows, but did not see the cl.exe issue. The notebook was able to find cl.exe and add it PATH without additional user inputs. Could you provide more details on how to reproduce the issue?
I have also updated the notebook and README on how to interact with the model and also included instructions on running with benchmark app as requested, please review when you get a chance. Thanks!

2022-06-09 17:09 UTC, karkadad commented
@ryanloney Please let me know if you had a chance to review this. Thanks

2022-06-20 08:32 UTC, Debskij requested changes
Hi @karkadad! Thanks for your contribution. I've added some changes to change inference to single line approach.

2022-06-20 08:32 UTC, Debskij commented on notebooks/216-knowledge-graphs-conve/216-knowledge-graphs-conve.ipynb
> +    "output_layer = compiled_model.output(0)\n",
```suggestion
    "input_layer_source = compiled_model.input('input.1')\n",
    "input_layer_relation = compiled_model.input('input.2')\n",
    "output_layer = compiled_model.output(0)\n",
```

2022-06-20 08:32 UTC, Debskij commented on notebooks/216-knowledge-graphs-conve/216-knowledge-graphs-conve.ipynb
> +    "    h, r, t = test_sample\n",
```suggestion
    "    source, relation, target = test_sample\n",
    "    model_inputs = {input_layer_source: source, input_layer_relation: relation}\n",
```

2022-06-20 08:32 UTC, Debskij commented on notebooks/216-knowledge-graphs-conve/216-knowledge-graphs-conve.ipynb
> +    "request = compiled_model.create_infer_request()\n",
```suggestion

```
Remove this line

2022-06-20 08:32 UTC, Debskij commented on notebooks/216-knowledge-graphs-conve/216-knowledge-graphs-conve.ipynb
> +    "    request.infer(inputs={'input.1': h, 'input.2': r})\n",
```suggestion
    "    result = compiled_model(model_inputs)[output_layer]\n",
```

2022-06-20 08:32 UTC, Debskij commented on notebooks/216-knowledge-graphs-conve/216-knowledge-graphs-conve.ipynb
> +    "    result = request.get_output_tensor(output_layer.index).data\n",
```suggestion

```
Remove this line

2022-06-20 15:02 UTC, ryanloney approved these changes

2022-06-29 15:37 UTC, Debskij approved these changes

2022-06-29 15:59 UTC, ryanloney commented
@karkadad there is another notebook called 216. Can you update this one? We also need to resolve the conflicts to hopefully trigger CI to run again

2022-07-01 01:15 UTC, karkadad commented
@ryanloney @Debskij Thanks for reviewing the notebook. I've updated the notebook number and resolved the conflicts.

2022-07-12 22:40 UTC, karkadad commented
@ryanloney @Debskij Looks like all the CI checks are passing, and also the notebook number is updated as well the conflicts are resolved now. Please review. Thanks

2022-07-12 23:10 UTC, ryanloney commented
Thanks @karkadad! We will merge this tomorrow. @paularamo can you do a quick check and approve (unless you see any issues)?

2022-07-13 13:39 UTC, paularamo approved these changes
Thanks for your contributions. I will merge it, my concern in the future is with Win 11, but this is something we will work on in the future.

2022-07-13 13:39 UTC, merged