Update contribute
openvinotoolkit/openvino_notebooks pull request #608
Opened 2022-08-10 12:41 UTC by AnishaUdayakumar

I have updated the recommendations for File structure regarding model, data, and License for the contributors.

2022-08-17 12:07 UTC, paularamo commented
@ryanloney, I have doubts about the data/models licensing terms to put here. Could you please give us your feedback on this? Thanks and BR

2022-08-23 21:30 UTC, ryanloney requested changes

2022-08-23 21:30 UTC, ryanloney commented on CONTRIBUTING.md
> +For any model/data used, ensure to have proper license to be used in this repository.
```suggestion
If you download or include a model, it must be licensed under an open source license like Apache 2.0 which allows for redistribution, modification and commercial use. 

Any datasets, images or videos used for fine-tuning, quantization or inference inside a notebook must be licensed under Creative Commons 4.0 (CC 4.0) with permission for commercial use. If commercial use is not allowed, but the data is under CC 4.0, special approval will be required. Please let us know in your pull request if your data has any restrictions on use.
```

2022-08-24 05:52 UTC, ryanloney approved these changes

2022-08-24 12:00 UTC, paularamo approved these changes

2022-08-24 12:00 UTC, merged