223-text-prediction-updated
openvinotoolkit/openvino_notebooks pull request #611
Opened 2022-08-17 11:18 UTC by dwipddalal

223-text-prediction-updated

2022-08-18 11:30 UTC, dwipddalal commented
Is this PR good or are there any changes that I need to make in this case?

2022-08-18 13:36 UTC, adrianboguszewski requested changes
Great work @dwipddalal! We need just minor changes. Please commit my suggestions as well as fix the notebook for CI to pass. All tests must be green to merge your PR. Run nbqa on your local machine to fix the issues below:
![Screenshot from 2022-08-18 14-35-17](https://user-images.githubusercontent.com/4547501/185408434-94322b93-5b1b-4f1a-a9e6-ed151df2cce7.png)

2022-08-18 13:36 UTC, adrianboguszewski commented on notebooks/223-text-prediction/README.md
> +In this demo we have used <b> Generative Pre-trained Transformer 2 ([GPT-2](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/gpt-2)) </b> model for text prediction.
```suggestion
In this demo we have used **Generative Pre-trained Transformer 2 ([GPT-2](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/gpt-2))** model for text prediction.
```

2022-08-18 13:36 UTC, adrianboguszewski commented on notebooks/223-text-prediction/README.md
> +
```suggestion
This is an interactive demonstration in which the user can type text into the input bar and generate predicted text. This procedure can be repeated as many times as the user desires.

```

2022-08-18 13:36 UTC, adrianboguszewski commented on notebooks/223-text-prediction/README.md
> +
```suggestion
```

2022-08-18 13:36 UTC, adrianboguszewski commented on notebooks/README.md
> +| [223-text-prediction](223-text-prediction/)<br> | Use Gpt-2 to perform text prediction on the input sequence |![image](https://user-images.githubusercontent.com/91228207/185105225-0f996b0b-0a3b-448
```suggestion
| [223-text-prediction](223-text-prediction/)<br> | Use Gpt-2 to perform text prediction on the input sequence | <img src=https://user-images.githubusercontent.com/91228207/185105225-0f996b0b-0a3b-4486-872d-364ac6fab68b.png  width=225> |
```

2022-08-18 13:36 UTC, adrianboguszewski commented on README.md
> +| [223-text-prediction](223-text-prediction/)<br> | Use Gpt-2 to perform text prediction on the input sequence |![image](https://user-images.githubusercontent.com/91228207/185105225-0f996b0b-0a3b-448
```suggestion
| [223-text-prediction](notebooks/223-text-prediction/)<br> | Use Gpt-2 to perform text prediction on the input sequence | <img src=https://user-images.githubusercontent.com/91228207/185105225-0f996b0b-0a3b-4486-872d-364ac6fab68b.png  width=225> |
```

2022-08-18 14:15 UTC, dwipddalal commented
> Great work @dwipddalal! We need just minor changes. Please commit my suggestions as well as fix the notebook for CI to pass. All tests must be green to merge your PR. Run nbqa on your local machine to check the issues below: ![Screenshot from 2022-08-18 14-35-17](https://user-images.githubusercontent.com/4547501/185408434-94322b93-5b1b-4f1a-a9e6-ed151df2cce7.png) Finally, clear your notebooks outputs by running: `jupyter nbconvert --clear-output --inplace 223-text-prediction.ipynb`

Sure. I shall resolve them as soon as possible.

2022-08-22 13:51 UTC, adrianboguszewski approved these changes

2022-08-22 15:53 UTC, adrianboguszewski commented on notebooks/223-text-prediction/223-text-prediction.ipynb
> +  },
```suggestion
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  }
 },
  },
```

2022-08-22 16:38 UTC, adrianboguszewski commented on notebooks/223-text-prediction/223-text-prediction.ipynb
> +  },
```suggestion
```

2022-08-22 16:42 UTC, adrianboguszewski commented on notebooks/223-text-prediction/223-text-prediction.ipynb
> +  }
```suggestion
  },
```

2022-08-24 13:39 UTC, dwipddalal commented
We need to pass these 18 test cases, right? If so, then I shall read about them in more detail and try to find the error.

2022-08-24 14:55 UTC, adrianboguszewski commented
Yes. We must find the cause of these errors and fix it.

2022-08-25 10:38 UTC, adrianboguszewski commented on notebooks/223-text-prediction/223-text-prediction.ipynb
> +    "        f\"--download_dir {base_model_dir} --output_dir {base_model_dir}\"\n",
```suggestion
    "        f\" --download_dir {base_model_dir} --output_dir {base_model_dir}\"\n",
```

2022-08-25 16:05 UTC, adrianboguszewski commented
@dwipddalal I found and fixed the issue. Other errors are related to external packages and will be fixed in another PR.

2022-08-25 21:07 UTC, dwipddalal commented
It's great to hear that. I shall try to remove the other errors.

2022-08-26 09:44 UTC, adrianboguszewski commented
Thanks for these changes. We have to merge #619 before this to fix CI issues.

2022-08-26 15:06 UTC, dwipddalal commented
So here, first, we shall merge the pr and then focus on fixing the remaining issues? For merging Ig, we shall first need approval from one more reviewer.

2022-08-26 17:20 UTC, dwipddalal commented
Okay.

2022-08-27 12:53 UTC, dwipddalal commented
If the issue of external packages is solved, then shall I once again push the previous commit?

2022-08-28 16:29 UTC, adrianboguszewski commented
You don't have to do anything related to external packages. But let's wait for the @ryanloney review.

2022-08-29 22:20 UTC, ryanloney requested changes
@dmatveev please review suggested changes and update the name of the directory and .ipynb to include "gpt2" 

223-gpt2-text-prediction
223-gpt2-text-prediction.ipynb

2022-08-30 10:55 UTC, dwipddalal commented
> @dwipddalal please review suggested changes and update the name of the directory and .ipynb to include "gpt2"
> 
> 223-gpt2-text-prediction 223-gpt2-text-prediction.ipynb

Changed both the file name as well as the folder name.

2022-08-30 11:01 UTC, adrianboguszewski commented on notebooks/223-text-prediction/README.md
> +This is an interactive demonstration in which the user can type text into the input bar and generate predicted text. This procedure can be repeated as many times as the user desires.
```suggestion
This is a demonstration in which the user can type the beginning of the text and the network will generate a further. This procedure can be repeated as many times as the user desires.
```

2022-08-30 11:01 UTC, adrianboguszewski commented on notebooks/223-gpt2-text-prediction/223-gpt2-text-prediction.ipynb
> +    "This notebook shows interactive text prediction with OpenVINO. We use the [GPT-2](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/gpt-2) model, which is a part of the
```suggestion
    "This notebook shows a text prediction with OpenVINO. We use the [GPT-2](https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/gpt-2) model, which is a part of the Generative Pre-trained Transformer (GPT) family. GPT-2 is pre-trained on a large corpus of English text using unsupervised training. The model is available from [Open Model Zoo](https://github.com/openvinotoolkit/open_model_zoo/), which we will use to download and convert the model to OpenVINO IR."
```

2022-08-30 14:30 UTC, dwipddalal commented
I am guessing the reason for the failure of two test cases is because of some issues with the external packages?

2022-08-30 14:50 UTC, adrianboguszewski commented
We don't for now. I'm trying to investigate.

2022-08-30 17:10 UTC, dwipddalal commented
It's great to see that all test cases got passed. Now I shall get good sleep.
I tried a lot to find the exact issue but wasn't able to find one.  I would really like to learn the problem that caused the issue, if it's not trouble for you can you please explain it?

2022-08-30 17:56 UTC, ryanloney approved these changes

2022-08-30 20:14 UTC, adrianboguszewski commented on notebooks/223-gpt2-text-prediction/README.md
> +Text generation is a type of natural language processing. It uses computational linguistics and artificial intelligence to automatically produce natural language text that can meet specific communica
```suggestion
Text generation is a type of natural language processing that uses computational linguistics and artificial intelligence to automatically produce text that can meet specific communicative needs.
```

2022-08-30 20:14 UTC, adrianboguszewski commented
It was a random error of CI.

2022-08-31 10:10 UTC, merged

2022-08-31 14:14 UTC, dwipddalal commented
Thanks a lots @adrianboguszewski and @ryanloney  for your help in improving the quality of the notebook. It feels very good to finally get my PR merged into the main branch.