Amazon SageMaker
openvinotoolkit/openvino_notebooks pull request #646
Opened 2022-10-17 23:39 UTC by tescal2

This is a pull request to add reference to Amazon SageMaker from the READ.ME page as well as the updated wiki page that uses an updated walk through using the Image Classification sample notebook within Amazon SageMaker Studio.

2022-10-18 16:49 UTC, adrianboguszewski commented
Thanks for this PR. Your changes should be also included in notebooks/README.md file. You refer to the AWS wiki, which doesn't exist. Are you going to provide the content for that page?

2022-10-18 17:19 UTC, tescal2 commented
> 



> Thanks for this PR. Your changes should be also included in notebooks/README.md file. You refer to the AWS wiki, which doesn't exist. Are you going to provide the content for that page?

@adrianboguszewski Great callout. I went ahead and committed the update to the notebooks/READ.ME as well as part of the PR. Also, the wiki page is authored and can be found here: https://github.com/tescal2/openvino_notebooks/wiki/Amazon-SageMaker

We will need to then remove an outdated version that already exists found here: https://github.com/openvinotoolkit/openvino_notebooks/wiki/Sagemaker

2022-10-20 11:27 UTC, adrianboguszewski requested changes
Is it possible to get the raw version of https://github.com/tescal2/openvino_notebooks/wiki/Amazon-SageMaker? It would be easier to copy it to our wiki

2022-10-20 11:27 UTC, adrianboguszewski commented on README.md
> +	* [Amazon SageMaker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/AWS)
```suggestion
	* [Amazon SageMaker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Amazon-SageMaker)
```

2022-10-20 11:27 UTC, adrianboguszewski commented on README.md
> +| [Windows](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows) | [Ubuntu](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu) | [macOS](https://github.com/openvinotool
```suggestion
| [Windows](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows) | [Ubuntu](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu) | [macOS](https://github.com/openvinotoolkit/openvino_notebooks/wiki/macOS) | [Red Hat](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Red-Hat-and-CentOS) | [CentOS](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Red-Hat-and-CentOS) | [Azure ML](https://github.com/openvinotoolkit/openvino_notebooks/wiki/AzureML) | [Docker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Docker) | [Amazon SageMaker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Amazon-SageMaker)|
```

2022-10-20 11:27 UTC, adrianboguszewski commented on notebooks/README.md
> +	* [Amazon SageMaker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/AWS)
```suggestion
	* [Amazon SageMaker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Amazon-SageMaker)
```

2022-10-20 11:27 UTC, adrianboguszewski commented on notebooks/README.md
> +| [Windows](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows) | [Ubuntu](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu) | [macOS](https://github.com/openvinotool
```suggestion
| [Windows](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Windows) | [Ubuntu](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Ubuntu) | [macOS](https://github.com/openvinotoolkit/openvino_notebooks/wiki/macOS) | [Red Hat](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Red-Hat-and-CentOS) | [CentOS](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Red-Hat-and-CentOS) | [Azure ML](https://github.com/openvinotoolkit/openvino_notebooks/wiki/AzureML) | [Docker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Docker) | [Amazon SageMaker](https://github.com/openvinotoolkit/openvino_notebooks/wiki/Amazon-SageMaker)|
```

2022-10-21 15:29 UTC, tescal2 commented
> @adrianboguszewski Great callout. I went ahead and

Does this work? https://raw.githubusercontent.com/wiki/tescal2/openvino_notebooks/Amazon-SageMaker.md

2022-10-21 15:39 UTC, adrianboguszewski commented
Yes. Thank you. Please let us test these instructions before we merge this PR.

2022-11-02 22:10 UTC, ryanloney commented
@tescal2 @adrianboguszewski 
Unfortunately, at this time, openvino-dev is built following manylinux_2_27 standard. This means pip install openvino-dev does not work on Amazon Linux. See below: 
![image](https://user-images.githubusercontent.com/15709723/199611482-179913ca-ecc7-4a22-b74b-2f7934171a4b.png)

We have an internal request to try building manylinux_2_17 (aka manylinux2014) python wheels using gcc10 for openvino-dev. Until we do this, you will need to build from source code. These are the instructions to do it: https://github.com/openvinotoolkit/openvino/wiki/Building-OpenVINO-on-CentOS-7-Guide

Until we can pip install openvino-dev on Amazon Linux, I don't think it makes sense to expose this guide. 

Anyone else have input? I hope we can get the install working soon!

-Ryan

2022-11-03 16:50 UTC, ryanloney commented
@tescal2 sorry for the confusion. We see the process we tested was outdated. Updating the wiki to use your new instructions. Then we can merge this

2022-11-03 16:58 UTC, ryanloney approved these changes
I updated the wiki page. @ravi9 is testing on his SageMaker instance, but these instructions were tested externally yesterday. I'm good to merge this as soon as one more approver reviews. 

@adrianboguszewski  @raymondlo84 can you take a look. Here is updated guide: https://github.com/openvinotoolkit/openvino_notebooks/wiki/SageMaker

2022-11-03 22:44 UTC, ryanloney commented
Ravi made updates to the guide. Let's get this merged tomorrow, if possible.

2022-11-04 10:09 UTC, adrianboguszewski approved these changes

2022-11-04 10:10 UTC, merged