Ea/paddle2onnx
openvinotoolkit/openvino_notebooks pull request #688
Opened 2022-11-30 13:31 UTC by eaidova

2022-12-01 06:49 UTC, ryanloney commented
I'm not able to suggest an edit for some reason on the beginning of notebook, but top of the .ipynb says "Convert a PaddlePaddle Model to ONNX and OpenVINO™ IR" Need to remove the ONNX part @eaidova

2022-12-01 06:59 UTC, ryanloney requested changes
Looks good except for a few minor changes (ONNX still showing up in a README, top of ipynb and one of the URL in README)

2022-12-01 06:59 UTC, ryanloney commented on notebooks/103-paddle-to-openvino/README.md
> + # PaddlePaddle to ONNX and OpenVINO™ IR Tutorial
```suggestion
 # PaddlePaddle to OpenVINO™ IR Tutorial
```

2022-12-01 06:59 UTC, ryanloney commented on README.md
> +| [103-paddle-to-openvino](notebooks/103-paddle-onnx-to-openvino/)<br>[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/openvinotoolkit/openvino_notebooks/HEAD?filepath=note
```suggestion
| [103-paddle-to-openvino](notebooks/103-paddle-to-openvino/)<br>[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/openvinotoolkit/openvino_notebooks/HEAD?filepath=notebooks%2F103-paddle-to-openvino%2F103-paddle-to-openvino-classification.ipynb) | Convert PaddlePaddle models to OpenVINO IR | 
```

2022-12-02 10:46 UTC, eaidova commented
> I'm not able to suggest an edit for some reason on the beginning of notebook, but top of the .ipynb says "Convert a PaddlePaddle Model to ONNX and OpenVINO™ IR" Need to remove the ONNX part @eaidova

@ryanloney  thank you, updated

2022-12-12 15:02 UTC, adrianboguszewski reviewed
According to the contributing guide, any image should go to "data" dir.

2022-12-12 15:15 UTC, eaidova commented
> According to the contributing guide, any image should go to "data" dir.

I just rename directory, image was located in the current dir in main branch https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/103-paddle-onnx-to-openvino/coco_close.png

2022-12-12 15:44 UTC, adrianboguszewski commented
> > According to the contributing guide, any image should go to "data" dir.
> 
> I just rename directory, image was located in the current dir in main branch https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/103-paddle-onnx-to-openvino/coco_close.png

Ok, I will create separate issue for that.

2022-12-12 16:00 UTC, eaidova commented
> > > According to the contributing guide, any image should go to "data" dir.
> > 
> > 
> > I just rename directory, image was located in the current dir in main branch https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/103-paddle-onnx-to-openvino/coco_close.png
> 
> Ok, I will create separate issue for that.

I moved image

2022-12-14 04:33 UTC, eaidova commented
@ryanloney do you have any additional comments?

2022-12-14 15:33 UTC, ryanloney requested changes
@eaidova please see my suggested edits

2022-12-14 15:33 UTC, ryanloney commented on notebooks/103-paddle-to-openvino/103-paddle-to-openvino-classification.ipynb
> +    "Set `IMAGE_FILENAME` to the filename of an image to use. Set `MODEL_NAME` to the PaddlePaddle model to download from PaddleHub. `MODEL_NAME` will also be the base name for the IR model. The note
```suggestion
    "Set `IMAGE_FILENAME` to the filename of an image to use. Set `MODEL_NAME` to the PaddlePaddle model to download from PaddleHub. `MODEL_NAME` will also be the base name for the IR model. The notebook is tested with the [mobilenet_v3_large_x1_0](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/en/models/Mobile_en.md) model. Other models may use different preprocessing methods and therefore require some modification to get the same results on the original and converted model.\n",
```

2022-12-14 15:33 UTC, ryanloney commented on notebooks/103-paddle-to-openvino/103-paddle-to-openvino-classification.ipynb
> +    "In the next cell, we load model, read and display an image, do inference on that image, and show the top three prediction results."
```suggestion
    "In the next cell, we load the model, load and display an image, do inference on that image, and then show the top 3 prediction results."
```

2022-12-14 15:33 UTC, ryanloney commented on notebooks/103-paddle-to-openvino/103-paddle-to-openvino-classification.ipynb
> +    "`classifier.predict()` takes an image file name, reads image and preprocesses input and returns the class labels and scores of the image. Preprocessing the image is done behind the scenes. The c
```suggestion
    "`classifier.predict()` takes an image file name, reads the image, preprocesses the input, then returns the class labels and scores of the image. Preprocessing the image is done behind the scenes. The classification model returns an array with floating point values for each of the 1000 ImageNet classes. The higher the value, the more confident the network is that the class number corresponding to that value (the index of that value in the network output array) is the class number for the image. \n",
```

2022-12-14 15:33 UTC, ryanloney commented on notebooks/103-paddle-to-openvino/103-paddle-to-openvino-classification.ipynb
> +    "The `classifier.get_config()` module shows preprocewssing configuration for model. it should be seen that images are normalized, resized and cropped and that the BGR image is converted to RGB be
```suggestion
    "The `classifier.get_config()` module shows the preprocessing configuration for the model. It should show that images are normalized, resized and cropped, and that the BGR image is converted to RGB before propagating it through the network. In the next cell, we get the `classifier.predictror.preprocess_ops` property that returns list of preprocessing operations to do inference on the OpenVINO IR model using the same method. "
```

2022-12-14 15:33 UTC, ryanloney commented on notebooks/103-paddle-to-openvino/103-paddle-to-openvino-classification.ipynb
> +    "For decoding lables predicted by model to names of classes, we need to have mapping between them, model config contains information about `class_id_map_file`, which store such mapping. The code
```suggestion
    "To decode the labels predicted by the model to names of classes, we need to have a mapping between them. The model config contains information about `class_id_map_file`, which stores such mapping. The code below shows how to parse the mapping into a dictionary to use with the OpenVINO model."
```

2022-12-14 22:51 UTC, ryanloney approved these changes

2022-12-15 06:57 UTC, merged