Move all data to common folder
openvinotoolkit/openvino_notebooks pull request #743
Opened 2022-12-29 14:17 UTC by sbalandi

2022-12-29 14:39 UTC, eaidova commented
@sbalandi general structure is good, thanks!
I have several suggestions regarding some files movements:
* data/text/vocab.txt -> data/text/bert-uncased/vocab.txt - I believe, in future we can have several files with the same name, so let's help to identify correctly model which this vocab corresponds.
* data/image/annotation and data/json/annotation -> data/datasets/person_detection (and place annotation and images in the same folder), it is parts of the same dataset, spliting them to different folders may confuse users

2022-12-29 20:10 UTC, sbalandi commented
looks like 208-optical-character-recognition.ipynb will be fail anyway because of this link:
`image_file = "https://github.com/openvinotoolkit/openvino_notebooks/raw/main/notebooks/data/image/intel_rnb.jpg" `
This link is on main branch, but in branch of this commit folder structure changed.

2022-12-30 04:56 UTC, eaidova commented
> image_file = "https://github.com/openvinotoolkit/openvino_notebooks/raw/main/notebooks/data/image/intel_rnb.jpg"

@sbalandi can we replace link with relative path?

2023-01-03 11:24 UTC, adrianboguszewski requested changes
Good job!
Please also change the name of the example.png file to something more meaningful (e.g., licence_plate)

2023-01-03 11:24 UTC, adrianboguszewski commented on notebooks/219-knowledge-graphs-conve/README.md
> +    <img src="../data/image/countries_knowledge_graph.png" width=500>
An URL of the image uploaded to Github should replace this like it's done in other README files. The countries_knowledge_graph.png file should be removed.

2023-01-04 15:29 UTC, adrianboguszewski approved these changes

2023-01-04 15:32 UTC, eaidova approved these changes

2023-01-04 15:53 UTC, adrianboguszewski commented
There is still usage in utils, which makes CI fail.

2023-01-05 05:41 UTC, merged