203 set dimension bound for dynamic shape
openvinotoolkit/openvino_notebooks pull request #779
Opened 2023-01-13 08:05 UTC by OpenVINO-dev-contest

set dimension bound for dynamic shape

2023-01-13 10:02 UTC, adrianboguszewski commented
What is the purpose of this change? Does it decrease memory usage?

2023-01-15 04:26 UTC, OpenVINO-dev-contest commented
> What is the purpose of this change? Does it decrease memory usage?

this is the method we official recommend to implement dynamic shape:
https://docs.openvino.ai/latest/openvino_docs_OV_UG_DynamicShapes.html#dimension-bounds

2023-01-16 13:20 UTC, adrianboguszewski requested changes

2023-01-16 13:20 UTC, adrianboguszewski commented on notebooks/203-meter-reader/203-meter-reader.ipynb
> +    "# seg_model_shape = {'image': [-1, 3, 512, 512]}\n",
Please remove that comment or add an explanation that this is an alternative. Commented code is very confusing. No one knows if it wasn't removed by mistake or if it was intentional.

2023-01-16 17:19 UTC, adrianboguszewski approved these changes

2023-01-18 03:33 UTC, eaidova approved these changes

2023-01-18 03:33 UTC, merged