README reorganization, new GIF and OS-specific guides
openvinotoolkit/openvino_notebooks pull request #92
Opened 2021-05-28 04:45 UTC by ryanloney

* Remove the Beta message
* Rearranged content on README
* Added Git to getting started list
* Moved OS-specific Install Guides to wiki
* Added buttons for Install Guides, linked to corresponding wiki page
* Added Run the Notebooks section with GIF
* Replaced jupyterlab.gif with notebooks.gif (longer clip) 
* Moved OS-specific troubleshooting to wiki pages

Let me know what you think.

2021-05-28 06:00 UTC, raymondlo84 requested changes
Hi Ryan, can you run the gif with this and get it under 5MB? 
https://ezgif.com/optimize

Now it's 20+MB and that's a bit too much?

2021-05-28 09:19 UTC, helena-intel commented
> Hi Ryan, can you run the gif with this and get it under 5MB?
> https://ezgif.com/optimize
> 
> Now it's 20+MB and that's a bit too much?

Good point. Can we make it an mp4? That's usually much smaller. Without additional context I also found it a bit confusing to see the Tensorflow Flowers notebook there, because when the gif caught my eye it just showed the output of the tensorflow training part, which could make someone think "did they just copy the tensorflow notebook?!"

2021-05-28 09:20 UTC, helena-intel commented on README.md
> +A collection of ready-to-run Jupyter\* notebooks for learning and experimenting with the OpenVINO™ Toolkit. The notebooks provide an introduction to OpenVINO basics and teach developers how to levera
It is not yet "this summer", to me we are still in Beta. We should at least have READMEs for every notebook before we are out of beta, in my opinion.

2021-05-28 09:23 UTC, helena-intel commented on README.md
> +- Git\*
Can we maybe remove this section? If we're adding git here, it starts to sound like this is a complete list. We have the install/preparation guides per OS too that will tell this, and the system requirements right below this.

2021-05-28 09:26 UTC, helena-intel commented on README.md
> +To reactivate your environment, simply repeat [Step 3](#step-3-activate-the-environment) from the Install Guide.
It is not required to reactivate the virtual environment to run the notebooks. Should we explain this? You need to reactivate the environment if you want to install new/updated packages. But just to run the notebooks, you can just do `jupyter lab notebooks` again.

2021-05-28 11:07 UTC, raymondlo84 commented
> > Hi Ryan, can you run the gif with this and get it under 5MB?
> > https://ezgif.com/optimize
> > Now it's 20+MB and that's a bit too much?
> 
> Good point. Can we make it an mp4? That's usually much smaller. Without additional context I also found it a bit confusing to see the Tensorflow Flowers notebook there, because when the gif caught my eye it just showed the output of the tensorflow training part, which could make someone think "did they just copy the tensorflow notebook?!"

I don't think mp4 plays properly in README. The last GIF I made was about 1.8MB so it's not that bad. =)

2021-06-03 22:39 UTC, helena-intel approved these changes

2021-06-03 22:40 UTC, merged